### ISSUE TITLE
Compatibility With HiFive Rev B

### ISSUE THREAD

**Issue by jmwright** [riscv-rust/hifive1#12]
Will this project be compatible with the [HiFive Rev B](https://www.sifive.com/boards/hifive1) that's now available for pre-order, which has the [FE310-G002](https://www.sifive.com/chip-designer#fe310) microprocessor?

**Comment by Disasm** [comment]
It should become compatible in the future. I am going to start working on this as soon as my Rev B arrives.

**Comment by Disasm** [comment]
Additionally, FE310-G002 seems to be backward-compatible with G000, so you can run programs that use "old" peripherals on G002 with minor changes (different flash size and .text start address).

**Comment by jmwright** [comment]
@Disasm Excellent, thank you.

**Comment by jmwright** [comment]
@Disasm Looks like my Rev B will be shipping on April 26th. I spend most of my time in Linux (Ubuntu 18.04 64-bit). Let me know if there's something I can do to help test.

**Comment by Disasm** [comment]
@jmwright Created a workspace for Rev B development: https://github.com/Disasm/hifive1-revb-workspace

**Comment by jmwright** [comment]
@Disasm Awesome, thanks. I will try it out.
