### ISSUE TITLE
Setup help for UART0 Machine Interrupts

### ISSUE THREAD

**Issue by dougli1sqrd** [riscv-rust/hifive1#21]
I have used the quick start guide to start a project writing code for the hifive1 revb board. I'm able to use `sprintln!` as in the examples to display text to the screen, as well as use the `Rx<UART0>` returned from the `configure()` function to read keyboard input and echo the input to the screen.

However, I'm using the `Rx` directly in the main loop, and I'd rather use Machine External interrupts to read from the UART0. Reading the e310 processor manual, as well as going through Stephen Marz's blog http://osblog.stephenmarz.com/ch2.html I can see how to interact with the UART, but these sources do not use the hifive1 rust crate.

I'm curious though if I can configure the UART for interrupts using the hifive1 crate API rather than direct memory mapping myself. So far in those experiments I haven't been successful yet in any case.

I understand how the PLIC receives input from peripherals and generates a machine external interrupt in the CPU, but I can't seem to manually configure it correctly, and I wonder if the hifive1 crate has an opinion on how I should be configuring the UART for interrupts.

Any guidance and help would be very helpful!

Feel free to examine my current state here: https://github.com/rustbox/rustbox-hifive1-revb/blob/main/src/main.rs

As you can see, I've gotten the timer interrupt to function properly using the riscv-rt crate and the `MachineTimer()` function.

**Comment by Disasm** [comment]
You can enable UART Rx interrupt by calling the `Serial::listen()` method. But then you have a bigger problem of configuring PLIC to actually receive and process the interrupt. You can look at https://github.com/riscv-rust/riscv-rust-quickstart/blob/interrupt-test/examples/interrupt.rs to learn how interrupt handling works with the current API.

**Comment by dougli1sqrd** [comment]
Oh awesome, thanks for the link! That makes a lot of sense.

One thing that I noticed is that in qemu emulation for the hifive1 board (I'm using built from source version 6.0.0) the interrupt example does not work. `COUNTER2` seems to never be incremented.

But when I uploaded the program to the board it works perfectly there. Does qemu-system-risc32 not implement MachineExternal interrupts, or perhaps I'm invoking qemu incorrectly?

```
qemu-system-riscv32 -nographic -machine sifive_e,revb=true -m 128M -drive if=none,format=raw,file=hdd.dsk,id=foo -serial 'mon:stdio' -bios none -kernel target/riscv32imac-unknown-none-elf/debug/examples/interrupt
```

**Comment by Disasm** [comment]
No idea, sorry. Maybe emulation is not precise or qemu platform you use doesn't have an RTC peripheral. You can ask this question on SiFive forums: https://forums.sifive.com/

**Comment by dougli1sqrd** [comment]
No worries!

I was ultimately able to get UART0 interrupts to work though! Thanks for the interrupt example link.

I think the main thing I was missing was setting the interrupt enable on the uart itself, as well as the "receive watermark level" in `rxctrl` of `UART0`.

Keyboard/UART interrupts work in qemu as well, just not the RTC timer.
