### ISSUE TITLE
Issue with REDV board and blue LED

### ISSUE THREAD

**Issue by romancardenas** [riscv-rust/hifive1#25]
While working with this crate and the REDV board, I found an error regarding the pin linked to the blue LED.
According to the [board schematic](https://cdn.sparkfun.com/assets/d/d/1/e/7/RedFive.pdf), this LED is connected to GPIO 5 (the same as the SPI1-SCK). That is why this crate links the blue LED with the GPIO 5. However, when trying to execute a blinky example, the LED did not blink.

So, looking closer to the board layout, I noticed that there is a 13 below the blue LED:
![layout](https://cdn.sparkfun.com//assets/parts/1/4/2/0/0/15594-SparkFun_RED-V_RedBoard_-_SiFive_RISC-V_FE310_SoC-01.jpg)

 I modified the blinky example to use the GPIO 13 and... voilà! It worked.

I'll do a couple of experiments more to find any other issue and submit a PR to fix this error.

**Comment by romancardenas** [comment]
Same issue with [REDV Thing Plus board](https://www.sparkfun.com/products/15799). According to its layout, the LED is in GPIO 5:
![board](https://cdn.sparkfun.com//assets/parts/1/4/4/0/8/15799-SparkFun_RED-V_Thing_Plus_-_SiFive_RISC-V_FE310_SoC-01.jpg).

However, this is not true. The LED blinks when I choose the GPIO 13.

**Comment by almindor** [comment]
This is odd because I'm 100% sure I tested the blinky example with my red-v board. I'll try to check this out today.

**Comment by romancardenas** [comment]
My bad. It seems that pin 5 is digital 13 in REDV. I don't know why it didn't work in first instance, but now everything works like a charm. Thanks a lot!
